### ISSUE TITLE
event path does not work in windows

### ISSUE THREAD

**Issue by tentkotta** [ashiina/lambda-local#32] opened 2016-08-03 05:39 UTC
Hi,
The path to event.js file is not constructed properly in windows.
Please fix it.

**Comment by ashiina** [comment] 2016-08-09 10:56
I would need more information to reproduce this. 
Please let me know what your input is, where your files are placed, and what the error output is.

**Comment by svenbluege** [comment] 2016-08-13 04:03
My command line for windows is this: 

```lambda-local -c -t 10 -l index.js -h handler -e event-samples/event.js```

Reading the event works for me.

**Comment by gpotter2** [comment] 2016-09-13 20:00
Works for me too...

**Comment by ashiina** [comment] 2016-09-15 01:37
Will close this issue. Please re-submit with a clear description of your environment and reproduction steps.

**Closed by ashiina** 2016-09-15 01:37 UTC
